# Base configs
baseurl: "https://yeekevin.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-196037638-1"

# UI configs
title: "Photography by Kevin Yee"
subtitle: "See the world through my eyes!"
author: "Kevin Yee"
header:
 title: "Photography"
 subtitle: "by Kevin Yee"
footer:
 name: "Hello, I'm Kevin"
 bio: "I'm a photographer for fun"
 github: "Want a website like this for yourself for free? Fork <a href=\"https://github.com/ramswaroop/photography\">this repo on github</a>"
web_design: "AJ"
social_urls:
  linkedin: "https://www.linkedin.com/in/kevinyee1"
  github: "https://github.com/YeeKevin"
