# Base configs
baseurl: "https://yeekevin.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Kevin Yee"
subtitle: "See the world through my eyes!"
author: "Kevin Yee"
header:
 title: "Photography"
 subtitle: "by Kevin Yee"
footer:
 name: "Hey there, my name is Kevin"
web_design: "AJ"
social_urls:
  linkedin: "https://www.linkedin.com/in/kevinyee1"
  github: "https://github.com/YeeKevin"
